[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/archive/*"
  to = "https://your-archive-site-name.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 